services:
  db:
    image: postgres:17.5-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-dev}
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: file-sharing-api:local
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./cmd/server/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public

volumes:
  pgdata_local:

networks:
  public:
    driver: bridge